export const lengthUnits = ['m', 'dm', 'cm', 'mm']
export const areaUnits = ['m^2', 'dm^2', 'cm^2', 'mm^2']
export const flowUnits = ['m^3/s', 'm^3/h']
export const velocityUnits = ['m/s', 'm/h', 'km/s', 'km/h']
export const frictionLossUnits = ['Pa/m', 'kPa/m']
export const pressureDropUnits = ['Pa', 'kPa']
